"""
MedQuery — PDF Report Exporter
Generates a professional medical consultation report from chat history.
Uses fpdf2 for PDF generation.
"""

from fpdf import FPDF
from datetime import datetime
import io
import re


class MedQueryPDF(FPDF):
    """Custom PDF class with MedQuery branding."""

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=25)

    def header(self):
        if self.page_no() > 1:
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(120, 120, 120)
            self.cell(0, 8, "MedQuery Medical Consultation Report", align="L")
            self.cell(0, 8, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
            self.set_draw_color(200, 200, 200)
            self.line(10, self.get_y(), 200, self.get_y())
            self.ln(5)

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10,
                  "Generated by MedQuery | For informational purposes only | Not a substitute for professional medical advice",
                  align="C")


def _sanitize(text):
    """Remove emoji and non-latin1 chars for fpdf2 default font compatibility."""
    # Replace common symbols
    text = text.replace("\u2014", " -- ")  # em dash
    text = text.replace("\u2013", " - ")   # en dash
    text = text.replace("\u2018", "'").replace("\u2019", "'")  # smart quotes
    text = text.replace("\u201c", '"').replace("\u201d", '"')
    text = text.replace("\u2022", " * ")   # bullet
    text = text.replace("\u2026", "...")    # ellipsis
    # Strip remaining non-latin1 (emoji etc.)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _get_grade_info(overall_pct):
    """Return grade letter and description."""
    if overall_pct >= 90:
        return "A", "Very high confidence"
    elif overall_pct >= 75:
        return "B", "High confidence"
    elif overall_pct >= 60:
        return "C", "Medium confidence"
    else:
        return "D", "Low confidence"


def generate_pdf_report(chat_history, doc_names=None):
    """
    Generate a formatted PDF report from chat history.

    Args:
        chat_history: list of dicts with 'role', 'content', optional 'sources', 'evaluation'
        doc_names: list of uploaded document filenames

    Returns:
        bytes — the PDF file content
    """
    pdf = MedQueryPDF()

    # ─── Cover Page ───────────────────────────────────────
    pdf.add_page()

    # Title block
    pdf.ln(40)
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(30, 60, 110)
    pdf.cell(0, 15, _sanitize("MedQuery"), align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 14)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 10, "Medical Consultation Report", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(10)
    pdf.set_draw_color(30, 60, 110)
    pdf.set_line_width(0.8)
    pdf.line(60, pdf.get_y(), 150, pdf.get_y())
    pdf.ln(15)

    # Meta info
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 8, f"Date: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", align="C", new_x="LMARGIN", new_y="NEXT")

    if doc_names:
        names_str = ", ".join(doc_names) if isinstance(doc_names, list) else str(doc_names)
        pdf.cell(0, 8, f"Documents Analyzed: {_sanitize(names_str)}", align="C", new_x="LMARGIN", new_y="NEXT")

    # Count Q&A pairs
    q_count = sum(1 for m in chat_history if m["role"] == "user")
    pdf.cell(0, 8, f"Questions Asked: {q_count}", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(20)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 8,
             "This report is generated by MedQuery, an AI-powered medical document assistant.",
             align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6,
             "It is for informational purposes only and does not constitute medical advice.",
             align="C", new_x="LMARGIN", new_y="NEXT")

    # ─── Q&A Pages ────────────────────────────────────────
    exchange_num = 0
    i = 0
    while i < len(chat_history):
        msg = chat_history[i]

        if msg["role"] == "user":
            exchange_num += 1
            question = msg["content"]

            # Find the assistant response that follows
            answer_msg = None
            if i + 1 < len(chat_history) and chat_history[i + 1]["role"] == "assistant":
                answer_msg = chat_history[i + 1]
                i += 1  # skip ahead past the answer

            pdf.add_page()

            # Exchange header
            pdf.set_font("Helvetica", "B", 14)
            pdf.set_text_color(30, 60, 110)
            pdf.cell(0, 10, f"Question {exchange_num}", new_x="LMARGIN", new_y="NEXT")
            pdf.set_draw_color(30, 60, 110)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(5)

            # Question block — blue background
            pdf.set_fill_color(230, 240, 255)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(20, 20, 20)
            pdf.multi_cell(0, 7, _sanitize(f"Q: {question}"), fill=True)
            pdf.ln(5)

            if answer_msg:
                answer = answer_msg["content"]

                # Answer block
                pdf.set_font("Helvetica", "", 10)
                pdf.set_text_color(30, 30, 30)
                pdf.multi_cell(0, 6, _sanitize(answer))
                pdf.ln(5)

                # Source citations
                if "sources" in answer_msg and answer_msg["sources"]:
                    pdf.set_font("Helvetica", "B", 10)
                    pdf.set_text_color(80, 80, 80)
                    pdf.cell(0, 7, "Source Citations:", new_x="LMARGIN", new_y="NEXT")
                    pdf.set_font("Helvetica", "I", 9)
                    for idx, src in enumerate(answer_msg["sources"]):
                        page = src.get("page", "N/A")
                        content = src.get("content", "")[:200]
                        pdf.set_text_color(60, 60, 60)
                        pdf.multi_cell(0, 5, _sanitize(f"  [{idx+1}] Page {page}: {content}"))
                    pdf.ln(3)

                # Evaluation scores
                if "evaluation" in answer_msg:
                    ev = answer_msg["evaluation"]
                    overall = ev.get("overall_pct", 0)
                    grade, grade_desc = _get_grade_info(overall)

                    # Grade badge
                    pdf.set_font("Helvetica", "B", 11)
                    if grade == "A":
                        pdf.set_text_color(0, 150, 0)
                    elif grade == "B":
                        pdf.set_text_color(180, 150, 0)
                    elif grade == "C":
                        pdf.set_text_color(200, 120, 0)
                    else:
                        pdf.set_text_color(200, 50, 50)

                    pdf.cell(0, 8, _sanitize(f"Confidence Grade: {grade} -- {grade_desc}"),
                             new_x="LMARGIN", new_y="NEXT")

                    # Score table
                    pdf.ln(2)
                    pdf.set_font("Helvetica", "B", 9)
                    pdf.set_text_color(60, 60, 60)
                    pdf.set_fill_color(240, 240, 240)

                    col_w = 45
                    headers = ["Faithfulness", "Relevance", "Precision", "Utilisation"]
                    values = [
                        f"{ev.get('faithfulness_pct', 0)}%",
                        f"{ev.get('answer_relevance_pct', 0)}%",
                        f"{ev.get('retrieval_precision_pct', 0)}%",
                        f"{ev.get('context_utilisation_pct', 0)}%"
                    ]

                    for h in headers:
                        pdf.cell(col_w, 7, h, border=1, fill=True, align="C")
                    pdf.ln()

                    pdf.set_font("Helvetica", "", 9)
                    pdf.set_text_color(30, 30, 30)
                    for v in values:
                        pdf.cell(col_w, 7, v, border=1, align="C")
                    pdf.ln()

                    pdf.set_font("Helvetica", "B", 10)
                    pdf.set_text_color(30, 60, 110)
                    pdf.cell(col_w * 4, 7, f"Overall RAG Score: {overall}%",
                             border=1, align="C")
                    pdf.ln(10)

        i += 1

    # ─── Generate bytes ───────────────────────────────────
    return pdf.output()
